### ISSUE TITLE
Make the application translatable

### ISSUE THREAD

**Issue by Gabriele69** [evilbunny2008/geocaching#2]
Device BQ Aquaris E4.5
UT RC Channel (2019w15)

Make the application translatable

**Comment by evilbunny2008** [comment]
I have no idea how to do translations in UT, any pointers would be appreciated.

**Comment by evilbunny2008** [comment]
I'm pretty sure I've made the app translatable and used automated translations as the basis.

I don't know how to switch languages in an app to test.

**Comment by Speiburger** [comment]
As you probably have guessed from my pull request, translations are working! I don't know how to change the language either but when I started the app it was all in German. The automatic translations are pretty bad to be honest, but they will serve as a good base for further translations from other users!

**Comment by evilbunny2008** [comment]
@Speiburger I merged your changes but didn't publish in case other translations were done, will publish today with your changes.
