### ISSUE TITLE
Takeover the App..

### ISSUE THREAD

**Issue by MalteKiefer** [evilbunny2008/geocaching#7]
If there are enough users who use this app, I would be willing to fork this app and offer it as a new app in the AppStore and continue the development accordingly.

**Comment by Speiburger** [comment]
Hi, I already created my fork when I saw your Issue. So far I just applied the 2 Pull requests and fixed the search as well as improving the date problem. The app is now working and needs further development. I would be happy if we could do this together!

**Comment by MalteKiefer** [comment]
Give me the link I will check it.

**Comment by Speiburger** [comment]
You can find the repo  [here](https://github.com/Speiburger/geocaching)
